### ISSUE TITLE
Bcap unable to change slave mode

### ISSUE THREAD

**Issue by whitesea1** [hiveground-ros-package/denso_bcap#1]
I realize it's been a number of years since you uploaded this, but we are in desperate need of help getting this package working. Right now we have a VP5243 robot and the DENSO rc7 controller. The issue we are running into is that ros can connect to the controller, and turn the motors on, but when it tries to set the slave mode it errors out. 

We have followed the DENSO guides for setting up ORIN control on the pendant, is there something we are missing?

**Comment by mahisorn** [comment]
Hi,

Do you have a slave mode license from Denso? You will need it to enable
slave mode.

## 

Mahisorn Wongphati
HiveGround Co., Ltd.
(Sent from my phone)

**Comment by whitesea1** [comment]
Would that not be the code for ORin? If so then then no we don't have one.

Thanks for the quick response!

**Comment by mahisorn** [comment]
It is a license key issued by Denso. You will need to pay for it. It is not
so expensive (if I remember correctly).

On Thu, Apr 28, 2016 at 9:46 AM, whitesea1 notifications@github.com wrote:

> Would that not be the code for ORin? If so then then no we don't have one.
> 
> Thanks for the quick response!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/hiveground-ros-package/denso_bcap/issues/1#issuecomment-215292539

## 

Mahisorn Wongphati
Co-founder
HiveGround Co., Ltd.
www.hiveground.com
+66-88-801-9585

**Comment by whitesea1** [comment]
When we have the key do we enter it onto the system extension page on the pendant? Also looking at the pendant there is a key listed at the top of that window, though I don't know if that is what you are referring to.

**Comment by mahisorn** [comment]
Yes, you have to enter it with pendent.
The listed key is not included slave mode control.

On Thu, Apr 28, 2016 at 9:53 AM, whitesea1 notifications@github.com wrote:

> When we have the key do we enter it onto the system extension page on the
> pendant? Also looking at the pendant there is a key listed at the top of
> that window, though I don't know if that is what you are referring to.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/hiveground-ros-package/denso_bcap/issues/1#issuecomment-215294377

## 

Mahisorn Wongphati
Co-founder
HiveGround Co., Ltd.
www.hiveground.com
+66-88-801-9585

**Comment by whitesea1** [comment]
Thank you for the help! I'll close this out.
